// Code generated by gotdgen, DO NOT EDIT.

package tg

import (
	"context"
	"fmt"

	"github.com/gotd/td/bin"
)

// No-op definition for keeping imports.
var _ = bin.Buffer{}
var _ = context.Background()
var _ = fmt.Stringer(nil)

// AccountResetAuthorizationRequest represents TL type `account.resetAuthorization#df77f3bc`.
//
// See https://core.telegram.org/method/account.resetAuthorization for reference.
type AccountResetAuthorizationRequest struct {
	// Hash field of AccountResetAuthorizationRequest.
	Hash int64
}

// AccountResetAuthorizationRequestTypeID is TL type id of AccountResetAuthorizationRequest.
const AccountResetAuthorizationRequestTypeID = 0xdf77f3bc

// Encode implements bin.Encoder.
func (r *AccountResetAuthorizationRequest) Encode(b *bin.Buffer) error {
	if r == nil {
		return fmt.Errorf("can't encode account.resetAuthorization#df77f3bc as nil")
	}
	b.PutID(AccountResetAuthorizationRequestTypeID)
	b.PutLong(r.Hash)
	return nil
}

// Decode implements bin.Decoder.
func (r *AccountResetAuthorizationRequest) Decode(b *bin.Buffer) error {
	if r == nil {
		return fmt.Errorf("can't decode account.resetAuthorization#df77f3bc to nil")
	}
	if err := b.ConsumeID(AccountResetAuthorizationRequestTypeID); err != nil {
		return fmt.Errorf("unable to decode account.resetAuthorization#df77f3bc: %w", err)
	}
	{
		value, err := b.Long()
		if err != nil {
			return fmt.Errorf("unable to decode account.resetAuthorization#df77f3bc: field hash: %w", err)
		}
		r.Hash = value
	}
	return nil
}

// Ensuring interfaces in compile-time for AccountResetAuthorizationRequest.
var (
	_ bin.Encoder = &AccountResetAuthorizationRequest{}
	_ bin.Decoder = &AccountResetAuthorizationRequest{}
)

// AccountResetAuthorization invokes method account.resetAuthorization#df77f3bc returning error if any.
//
// See https://core.telegram.org/method/account.resetAuthorization for reference.
func (c *Client) AccountResetAuthorization(ctx context.Context, request *AccountResetAuthorizationRequest) (BoolClass, error) {
	var result BoolBox
	if err := c.rpc.InvokeRaw(ctx, request, &result); err != nil {
		return nil, err
	}
	return result.Bool, nil
}
