// Code generated by gotdgen, DO NOT EDIT.

package tg

import (
	"context"
	"fmt"
	"strings"

	"github.com/gotd/td/bin"
)

// No-op definition for keeping imports.
var _ = bin.Buffer{}
var _ = context.Background()
var _ = fmt.Stringer(nil)
var _ = strings.Builder{}

// FileHashVector is a box for Vector<FileHash>
type FileHashVector struct {
	// Elements of Vector<FileHash>
	Elems []FileHash
}

// FileHashVectorTypeID is TL type id of FileHashVector.
const FileHashVectorTypeID = bin.TypeVector

func (vec *FileHashVector) Zero() bool {
	if vec == nil {
		return true
	}
	if !(vec.Elems == nil) {
		return false
	}

	return true
}

// String implements fmt.Stringer.
func (vec *FileHashVector) String() string {
	if vec == nil {
		return "FileHashVector(nil)"
	}
	var sb strings.Builder
	sb.WriteString("FileHashVector")
	sb.WriteByte('[')
	for _, e := range vec.Elems {
		sb.WriteString(fmt.Sprint(e) + ",\n")
	}
	sb.WriteByte(']')
	return sb.String()
}

// TypeID returns MTProto type id (CRC code).
// See https://core.telegram.org/mtproto/TL-tl#remarks.
func (vec *FileHashVector) TypeID() uint32 {
	return FileHashVectorTypeID
}

// Encode implements bin.Encoder.
func (vec *FileHashVector) Encode(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't encode Vector<FileHash> as nil")
	}
	b.PutVectorHeader(len(vec.Elems))
	for idx, v := range vec.Elems {
		if err := v.Encode(b); err != nil {
			return fmt.Errorf("unable to encode Vector<FileHash>: field Elems element with index %d: %w", idx, err)
		}
	}
	return nil
}

// GetElems returns value of Elems field.
func (vec *FileHashVector) GetElems() (value []FileHash) {
	return vec.Elems
}

// Decode implements bin.Decoder.
func (vec *FileHashVector) Decode(b *bin.Buffer) error {
	if vec == nil {
		return fmt.Errorf("can't decode Vector<FileHash> to nil")
	}
	{
		headerLen, err := b.VectorHeader()
		if err != nil {
			return fmt.Errorf("unable to decode Vector<FileHash>: field Elems: %w", err)
		}
		for idx := 0; idx < headerLen; idx++ {
			var value FileHash
			if err := value.Decode(b); err != nil {
				return fmt.Errorf("unable to decode Vector<FileHash>: field Elems: %w", err)
			}
			vec.Elems = append(vec.Elems, value)
		}
	}
	return nil
}

// Ensuring interfaces in compile-time for FileHashVector.
var (
	_ bin.Encoder = &FileHashVector{}
	_ bin.Decoder = &FileHashVector{}
)
