// Code generated by gotdgen, DO NOT EDIT.

package tg

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"go.uber.org/multierr"

	"github.com/gotd/td/bin"
	"github.com/gotd/td/tdjson"
	"github.com/gotd/td/tdp"
	"github.com/gotd/td/tgerr"
)

// No-op definition for keeping imports.
var (
	_ = bin.Buffer{}
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = multierr.AppendInto
	_ = sort.Ints
	_ = tdp.Format
	_ = tgerr.Error{}
	_ = tdjson.Encoder{}
)

// StoriesGetPinnedStoriesRequest represents TL type `stories.getPinnedStories#b471137`.
//
// See https://core.telegram.org/method/stories.getPinnedStories for reference.
type StoriesGetPinnedStoriesRequest struct {
	// UserID field of StoriesGetPinnedStoriesRequest.
	UserID InputUserClass
	// OffsetID field of StoriesGetPinnedStoriesRequest.
	OffsetID int
	// Limit field of StoriesGetPinnedStoriesRequest.
	Limit int
}

// StoriesGetPinnedStoriesRequestTypeID is TL type id of StoriesGetPinnedStoriesRequest.
const StoriesGetPinnedStoriesRequestTypeID = 0xb471137

// Ensuring interfaces in compile-time for StoriesGetPinnedStoriesRequest.
var (
	_ bin.Encoder     = &StoriesGetPinnedStoriesRequest{}
	_ bin.Decoder     = &StoriesGetPinnedStoriesRequest{}
	_ bin.BareEncoder = &StoriesGetPinnedStoriesRequest{}
	_ bin.BareDecoder = &StoriesGetPinnedStoriesRequest{}
)

func (g *StoriesGetPinnedStoriesRequest) Zero() bool {
	if g == nil {
		return true
	}
	if !(g.UserID == nil) {
		return false
	}
	if !(g.OffsetID == 0) {
		return false
	}
	if !(g.Limit == 0) {
		return false
	}

	return true
}

// String implements fmt.Stringer.
func (g *StoriesGetPinnedStoriesRequest) String() string {
	if g == nil {
		return "StoriesGetPinnedStoriesRequest(nil)"
	}
	type Alias StoriesGetPinnedStoriesRequest
	return fmt.Sprintf("StoriesGetPinnedStoriesRequest%+v", Alias(*g))
}

// FillFrom fills StoriesGetPinnedStoriesRequest from given interface.
func (g *StoriesGetPinnedStoriesRequest) FillFrom(from interface {
	GetUserID() (value InputUserClass)
	GetOffsetID() (value int)
	GetLimit() (value int)
}) {
	g.UserID = from.GetUserID()
	g.OffsetID = from.GetOffsetID()
	g.Limit = from.GetLimit()
}

// TypeID returns type id in TL schema.
//
// See https://core.telegram.org/mtproto/TL-tl#remarks.
func (*StoriesGetPinnedStoriesRequest) TypeID() uint32 {
	return StoriesGetPinnedStoriesRequestTypeID
}

// TypeName returns name of type in TL schema.
func (*StoriesGetPinnedStoriesRequest) TypeName() string {
	return "stories.getPinnedStories"
}

// TypeInfo returns info about TL type.
func (g *StoriesGetPinnedStoriesRequest) TypeInfo() tdp.Type {
	typ := tdp.Type{
		Name: "stories.getPinnedStories",
		ID:   StoriesGetPinnedStoriesRequestTypeID,
	}
	if g == nil {
		typ.Null = true
		return typ
	}
	typ.Fields = []tdp.Field{
		{
			Name:       "UserID",
			SchemaName: "user_id",
		},
		{
			Name:       "OffsetID",
			SchemaName: "offset_id",
		},
		{
			Name:       "Limit",
			SchemaName: "limit",
		},
	}
	return typ
}

// Encode implements bin.Encoder.
func (g *StoriesGetPinnedStoriesRequest) Encode(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't encode stories.getPinnedStories#b471137 as nil")
	}
	b.PutID(StoriesGetPinnedStoriesRequestTypeID)
	return g.EncodeBare(b)
}

// EncodeBare implements bin.BareEncoder.
func (g *StoriesGetPinnedStoriesRequest) EncodeBare(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't encode stories.getPinnedStories#b471137 as nil")
	}
	if g.UserID == nil {
		return fmt.Errorf("unable to encode stories.getPinnedStories#b471137: field user_id is nil")
	}
	if err := g.UserID.Encode(b); err != nil {
		return fmt.Errorf("unable to encode stories.getPinnedStories#b471137: field user_id: %w", err)
	}
	b.PutInt(g.OffsetID)
	b.PutInt(g.Limit)
	return nil
}

// Decode implements bin.Decoder.
func (g *StoriesGetPinnedStoriesRequest) Decode(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't decode stories.getPinnedStories#b471137 to nil")
	}
	if err := b.ConsumeID(StoriesGetPinnedStoriesRequestTypeID); err != nil {
		return fmt.Errorf("unable to decode stories.getPinnedStories#b471137: %w", err)
	}
	return g.DecodeBare(b)
}

// DecodeBare implements bin.BareDecoder.
func (g *StoriesGetPinnedStoriesRequest) DecodeBare(b *bin.Buffer) error {
	if g == nil {
		return fmt.Errorf("can't decode stories.getPinnedStories#b471137 to nil")
	}
	{
		value, err := DecodeInputUser(b)
		if err != nil {
			return fmt.Errorf("unable to decode stories.getPinnedStories#b471137: field user_id: %w", err)
		}
		g.UserID = value
	}
	{
		value, err := b.Int()
		if err != nil {
			return fmt.Errorf("unable to decode stories.getPinnedStories#b471137: field offset_id: %w", err)
		}
		g.OffsetID = value
	}
	{
		value, err := b.Int()
		if err != nil {
			return fmt.Errorf("unable to decode stories.getPinnedStories#b471137: field limit: %w", err)
		}
		g.Limit = value
	}
	return nil
}

// GetUserID returns value of UserID field.
func (g *StoriesGetPinnedStoriesRequest) GetUserID() (value InputUserClass) {
	if g == nil {
		return
	}
	return g.UserID
}

// GetOffsetID returns value of OffsetID field.
func (g *StoriesGetPinnedStoriesRequest) GetOffsetID() (value int) {
	if g == nil {
		return
	}
	return g.OffsetID
}

// GetLimit returns value of Limit field.
func (g *StoriesGetPinnedStoriesRequest) GetLimit() (value int) {
	if g == nil {
		return
	}
	return g.Limit
}

// StoriesGetPinnedStories invokes method stories.getPinnedStories#b471137 returning error if any.
//
// See https://core.telegram.org/method/stories.getPinnedStories for reference.
func (c *Client) StoriesGetPinnedStories(ctx context.Context, request *StoriesGetPinnedStoriesRequest) (*StoriesStories, error) {
	var result StoriesStories

	if err := c.rpc.Invoke(ctx, request, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
